### ISSUE TITLE
want to know more specific about the whole workflow

### ISSUE THREAD

**Issue by chivas1000** [huhanwj/RT-WIFI-CSI#3]
well, i somehow confused with how you operate your work.
Is that first merging the two projects together(using the code merging sofware?) and then build the merged project.
then you address the error and go to the error file to fix it or how?
want a clearly explain...

**Comment by chivas1000** [comment]
and i got an error cloning this repo...

**Comment by chivas1000** [comment]
PLUS, don't know how to build the project

**Comment by chivas1000** [comment]
well, I'm using make command, is that a build process?
(but it takes a very long time to run...) @huhanwj

**Comment by huhanwj** [comment]
> 
> 
> well, i somehow confused with how you operate your work.
> Is that first merging the two projects together(using the code merging sofware?) and then build the merged project.
> then you address the error and go to the error file to fix it or how?
> want a clearly explain...

Yep basically that is how it works. But instead of simply "merging" them together, you need to check the different parts of the files (here we typically focus on its networking drivers and APIs, especially parts related to ath9k), identifying which parts are "real" differences instead of normal kernel updates or driver updates.

**How to detect errors?**
Buy build the kernel and read the build log. In the log, it will tell you which line makes the error. And then you can check the place directly or go even further to the functions it used, etc.

>well, I'm using make command, is that a build process?
>(but it takes a very long time to run...) @huhanwj

For this question, since this is based on the *Atheros CSI tool*. I suggest you to go and take a look at its user guide (already provided in readme).

**Comment by huhanwj** [comment]
> 
> 
> well, I'm using make command, is that a build process?
> (but it takes a very long time to run...) @huhanwj

This project has about 800M in size, which means basically an entire kernel. So build it will take time.
For your reference, I use a Intel Core i5-9600K (6 core processor) to build it and it will take about several minutes to finish (with errors now).

**Comment by huhanwj** [comment]
> 
> 
> well, I'm using make command, is that a build process?
> (but it takes a very long time to run...) @huhanwj

using make -j6 (as I am using a 6 core processor, no hyperthreading so the number is 6) will save time
You can modify the number by yourself following the number of threads that your CPU have.

**Comment by chivas1000** [comment]
> 
> 
> > well, I'm using make command, is that a build process?
> > (but it takes a very long time to run...) @huhanwj
> 
> using `make -j6` (as I am using a 6 core processor, no hyperthreading so the number is 6) will save time
> You can modify the number by yourself following the number of threads that your CPU have.

Fine, my oldschool computer just got a 4720HQ...the build just had finished...takes about 1hrs run in virtualbox...I would try use make -j later, THX.

**Comment by huhanwj** [comment]
> 
> 
> > > well, I'm using make command, is that a build process?
> > > (but it takes a very long time to run...) @huhanwj
> > 
> > 
> > using `make -j6` (as I am using a 6 core processor, no hyperthreading so the number is 6) will save time
> > You can modify the number by yourself following the number of threads that your CPU have.
> 
> Fine, my oldschool computer just got a 4720HQ...the build just had finished...takes about 1hrs run in virtualbox...I would try use make -j later, THX.

OK 4720HQ is a 4 core 8 thread processor, but considering that you are using a VM, it will depend how many CPU cores that you allocate to the VM instead of the real number of cores/threads. My desktop is running on linux so it can take all the computing power of my Core i5.
